### ISSUE TITLE
data did not match any variant of untagged enum 

### ISSUE THREAD

**Issue by BlackTea-c** [ezelikman/quiet-star#14]
Traceback (most recent call last):
  File "D:\LLM_Personalization\quiet-star\quiet-star-train.py", line 13, in <module>
    from eval_helpers import preprocess_eval_function_gsm, preprocess_eval_function_csqa, preprocess_function, compute_metrics, truncate_or_pad
  File "D:\LLM_Personalization\quiet-star\eval_helpers.py", line 5, in <module>
    initial_tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-v0.1",se_auth_token=token, force_download=True)
  File "D:\minicondaforme\envs\quiet\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 814, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "D:\minicondaforme\envs\quiet\lib\site-packages\transformers\tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
  File "D:\minicondaforme\envs\quiet\lib\site-packages\transformers\tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\minicondaforme\envs\quiet\lib\site-packages\transformers\models\llama\tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "D:\minicondaforme\envs\quiet\lib\site-packages\transformers\tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 40 column 3

**Comment by Indolent-Kawhi** [comment]
一样的问题，请问你解决了么？好像是 tokenizer 版本不兼容的问题
